-- MySQL Script generated by MySQL Workbench
-- Tue Jul  6 23:37:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `email` VARCHAR(300) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`story`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`story` (
  `story_id` INT UNSIGNED NOT NULL,
  `user_id` VARCHAR(300) NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NOT NULL,
  `created_on` DATETIME NOT NULL,
  PRIMARY KEY (`story_id`),
  INDEX `story_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `story_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`story_user_reaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`story_user_reaction` (
  `story_id` INT NOT NULL,
  `user_id` VARCHAR(300) NOT NULL,
  `reaction_type_id` VARCHAR(10) NOT NULL COMMENT 'We shoould consider having this one as restricted to a set of values allowed, I mean, only a few values should be allowed to be here.',
  PRIMARY KEY (`story_id`, `user_id`),
  INDEX `story_user_reaction_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `story_user_reaction_story_id`
    FOREIGN KEY (`story_id`)
    REFERENCES `mydb`.`story` (`story_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `story_user_reaction_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`story_user_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`story_user_comment` (
  `story_id` INT NOT NULL,
  `user_id` VARCHAR(300) NOT NULL,
  `commented_on` DATETIME NOT NULL,
  `body` TEXT NULL,
  `story_user_commentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`story_id`, `user_id`, `commented_on`),
  INDEX `story_user_comment_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `story_user_comment_story_id`
    FOREIGN KEY (`story_id`)
    REFERENCES `mydb`.`story` (`story_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `story_user_comment_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
